stages:
  - lint
  - publish

variables:
  APKG_SERVER: "https://apkg-dev.aiursoft.com"
  APKG_API_KEY: "2M43WwUQ7vWmxbELA53ZUCVxNJ0YXiwMZfgfS7KNSP0"

.lint:
  stage: lint
  before_script:
    - dotnet tool update -g aiursoft.apkg.client --configfile ./nuget.config || dotnet tool install -g aiursoft.apkg.client --configfile ./nuget.config
    - export PATH="$PATH:$HOME/.dotnet/tools"
    - apkg --version
  script:
    - cd $PACKAGE_DIR
    - apkg lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH != "master"

.publish:
  stage: publish
  before_script:
    - dotnet tool update -g aiursoft.apkg.client --configfile ./nuget.config || dotnet tool install -g aiursoft.apkg.client --configfile ./nuget.config
    - export PATH="$PATH:$HOME/.dotnet/tools"
    - apkg --version
  script:
    - cd $PACKAGE_DIR
    - apkg publish
    - APKG_FILE=$(ls bin/*.apkg 2>/dev/null | head -1)
    - '[ -n "$APKG_FILE" ] && apkg push -f "$APKG_FILE" -s "$APKG_SERVER" -k "$APKG_API_KEY" --skip-duplicate'
  rules:
    - if: $CI_COMMIT_BRANCH == "master"

base-files:
  extends: .publish
  variables:
    PACKAGE_DIR: base-files

plymouth-theme-spinner:
  extends: .publish
  variables:
    PACKAGE_DIR: plymouth-theme-spinner

anduinos-apt-config:
  extends: .publish
  variables:
    PACKAGE_DIR: anduinos-apt-config

anduinos-archive-keyring:
  extends: .publish
  variables:
    PACKAGE_DIR: anduinos-archive-keyring

anduinos-fluent-gtk-theme:
  extends: .publish
  variables:
    PACKAGE_DIR: anduinos-fluent-gtk-theme

anduinos-fluent-icon-theme:
  extends: .publish
  variables:
    PACKAGE_DIR: anduinos-fluent-icon-theme

anduinos-dconf-defaults:
  extends: .publish
  variables:
    PACKAGE_DIR: anduinos-dconf-defaults

gnome-shell-extension-anduinos-loc:
  extends: .publish
  variables:
    PACKAGE_DIR: gnome-shell-extension-anduinos-loc

gnome-shell-extension-anduinos-switcher:
  extends: .publish
  variables:
    PACKAGE_DIR: gnome-shell-extension-anduinos-switcher

gnome-shell-extension-noti-bottom-right:
  extends: .publish
  variables:
    PACKAGE_DIR: gnome-shell-extension-noti-bottom-right

gnome-shell-extension-accent-gtk-theme:
  extends: .publish
  variables:
    PACKAGE_DIR: gnome-shell-extension-accent-gtk-theme

gnome-shell-extension-accent-user-theme:
  extends: .publish
  variables:
    PACKAGE_DIR: gnome-shell-extension-accent-user-theme

gnome-shell-extension-accent-icons-theme:
  extends: .publish
  variables:
    PACKAGE_DIR: gnome-shell-extension-accent-icons-theme

gnome-shell-extension-arcmenu:
  extends: .publish
  variables:
    PACKAGE_DIR: gnome-shell-extension-arcmenu

gnome-shell-extension-blur-my-shell:
  extends: .publish
  variables:
    PACKAGE_DIR: gnome-shell-extension-blur-my-shell

gnome-shell-extension-clipboard-indicator:
  extends: .publish
  variables:
    PACKAGE_DIR: gnome-shell-extension-clipboard-indicator

gnome-shell-extension-customize-ibus:
  extends: .publish
  variables:
    PACKAGE_DIR: gnome-shell-extension-customize-ibus

gnome-shell-extension-dash-to-panel-anduinos:
  extends: .publish
  variables:
    PACKAGE_DIR: gnome-shell-extension-dash-to-panel-anduinos

gnome-shell-extension-lockkeys:
  extends: .publish
  variables:
    PACKAGE_DIR: gnome-shell-extension-lockkeys

gnome-shell-extension-mediacontrols:
  extends: .publish
  variables:
    PACKAGE_DIR: gnome-shell-extension-mediacontrols

gnome-shell-extension-network-stats:
  extends: .publish
  variables:
    PACKAGE_DIR: gnome-shell-extension-network-stats

gnome-shell-extension-proxy-switcher:
  extends: .publish
  variables:
    PACKAGE_DIR: gnome-shell-extension-proxy-switcher

gnome-shell-extension-simple-weather:
  extends: .publish
  variables:
    PACKAGE_DIR: gnome-shell-extension-simple-weather

gnome-shell-extension-tiling-assistant:
  extends: .publish
  variables:
    PACKAGE_DIR: gnome-shell-extension-tiling-assistant

anduinos-templates:
  extends: .publish
  variables:
    PACKAGE_DIR: anduinos-templates

anduinos-gnome-shell-locale:
  extends: .publish
  variables:
    PACKAGE_DIR: anduinos-gnome-shell-locale

anduinos-gnome-extensions:
  extends: .publish
  variables:
    PACKAGE_DIR: anduinos-gnome-extensions
