[org/gnome/shell/extensions/tiling-assistant]
activate-layout0=@as []
activate-layout1=@as []
activate-layout2=@as []
activate-layout3=@as []
auto-tile=@as []
center-window=@as []
debugging-free-rects=@as []
debugging-show-tiled-rects=@as []
default-move-mode=0
dynamic-keybinding-behaviour=0
import-layout-examples=false
last-version-installed=54
restore-window=@as []
search-popup-layout=@as []
tile-bottom-half=@as []
tile-bottomleft-quarter=@as []
tile-bottomright-quarter=@as []
tile-edit-mode=@as []
tile-left-half=['<Super>Left']
tile-maximize=@as []
tile-maximize-horizontally=@as []
tile-maximize-vertically=@as []
tile-right-half=['<Super>Right']
tile-top-half=@as []
tile-topleft-quarter=@as []
tile-topright-quarter=@as []
toggle-always-on-top=@as []
toggle-tiling-popup=@as []

