#!/bin/sh

PREREQ=""
prereqs() { echo "$PREREQ"; }
case $1 in prereqs) prereqs; exit 0 ;; esac

for x in $(cat /proc/cmdline); do
    case $x in
        timezone=*)
            TZ="${x#timezone=}"
            ;;
    esac
done

if [ -n "$TZ" ] && [ -f "/root/usr/share/zoneinfo/$TZ" ]; then
    rm -f /root/etc/localtime /root/etc/timezone
    ln -s "/usr/share/zoneinfo/$TZ" "/root/etc/localtime"
    echo "$TZ" > /root/etc/timezone

    chroot /root debconf-communicate >/dev/null 2>&1 <<EOF
set tzdata/Zones/$TZ $TZ
set tzdata/Areas ${TZ%%/*}
EOF
fi
