[org/gnome/shell/extensions/arcmenu]
arc-menu-icon=71
arcmenu-hotkey=['Super_L', 'Super_R']
button-padding=6
context-menu-items=[{'id': 'org.gnome.Nautilus.desktop'}, {'id': 'org.gnome.Ptyxis.desktop'}, {'id': 'org.gnome.Settings.desktop'}, {'id': 'org.gnome.Extensions.desktop'}, {'name': 'Separator', 'icon': 'list-remove-symbolic', 'id': 'ArcMenu_Separator'}, {'id': 'ArcMenu_Settings', 'name': 'ArcMenu Settings', 'icon': 'ArcMenu_ArcMenuIcon'}, {'id': 'ArcMenu_PanelExtensionSettings', 'name': 'Panel Extension Settings', 'icon': 'application-x-addon-symbolic'}, {'id': 'ArcMenu_Separator', 'name': 'Separator', 'icon': 'list-remove-symbolic'}, {'id': 'ArcMenu_PowerOptions', 'name': 'Power Options', 'icon': 'system-shutdown-symbolic'}, {'id': 'ArcMenu_ActivitiesOverview', 'name': 'Activities Overview', 'icon': 'view-fullscreen-symbolic'}, {'id': 'gnome-search-panel.desktop'}, {'id': 'ArcMenu_ShowDesktop', 'name': 'Show Desktop', 'icon': 'computer-symbolic'}]
custom-menu-button-icon='/usr/share/gnome-shell/extensions/arcmenu@arcmenu.com/icons/anduinos-logo.svg'
custom-menu-button-icon-size=32.0
dash-to-panel-standalone=true
distro-icon=5
eleven-layout-extra-shortcuts=[{'icon': 'org.gnome.Nautilus', 'id': 'org.gnome.Nautilus.desktop'}, {'icon': 'org.gnome.Ptyxis', 'id': 'org.gnome.Ptyxis.desktop'}, {'id': 'org.gnome.Settings.desktop'}]
enable-menu-hotkey=true
force-menu-location='BottomCentered'
left-panel-width=375
menu-button-appearance='Icon'
menu-button-icon='/usr/share/gnome-shell/extensions/arcmenu@arcmenu.com/icons/anduinos-logo.svg'
menu-button-icon-size=34
menu-button-padding=7
menu-button-position-offset=0
menu-height=650
menu-layout='11'
multi-monitor=true
override-menu-theme=false
pinned-apps=[{'id': 'firefox.desktop'}, {'id': 'org.gnome.Nautilus.desktop'}, {'id': 'org.gnome.Ptyxis.desktop'}, {'id': 'org.gnome.Software.desktop'}, {'id': 'org.gnome.Loupe.desktop'}, {'id': 'org.gnome.Snapshot.desktop'}, {'id': 'org.gnome.Weather.desktop'}, {'id': 'org.gnome.TextEditor.desktop'}, {'id': 'org.gnome.clocks.desktop'}, {'id': 'org.gnome.Calculator.desktop'}, {'id': 'org.gnome.Calendar.desktop'}, {'id': 'org.gnome.Papers.desktop'}, {'id': 'io.github.celluloid_player.Celluloid.desktop'}, {'id': 'org.gnome.seahorse.Application.desktop'}, {'id': 'org.gnome.Music.desktop'}, {'id': 'org.gnome.baobab.desktop'}, {'id': 'org.gnome.Settings.desktop'}, {'id': 'net.nokyan.Resources.desktop'}]
position-in-panel='Center'
prefs-visible-page=0
recently-installed-apps=['firefox.desktop']
right-panel-width=200
search-entry-border-radius=(true, 25)
show-activities-button=false
show-update-notification-v64=false
update-notifier-project-version=73

