# GTK4 Desktop Icons NG (DING) Extension Settings
[org/gnome/shell/extensions/gtk4-ding]
add-volumes-opposite=true
dark-text-in-labels=false
free-position-icons=false
show-drop-place=true
show-home=true
show-network-volumes=false
show-trash=true
start-corner='top-left'
